### PR TITLE
add unique users graph

### PR DESCRIPTION
**Pull request by marknye-at-illinois**
Count and graph unique users per minute.

### CODE REVIEW

**Comment by jhoerr** [comment]
Is the idea here that we want to count the number of unique users engaging w/ Box in the last minute via the events that we captured?

**Comment by marknye-at-illinois** [comment]
Yep, exactly right.

**Comment by jhoerr** [comment]
Ok, cool. I noticed you created a new chart for it. What would you think of adding this as a 4th series of the 'Engagement' chart?

**Comment by jhoerr** [comment]
I'm just trying to think about presentation balance. If they are conceptually different from one another, we could do something like:

```
[   File Events   ][   Engage Events   ]
[          Unique User Events          ]
[   File Totals   ][   Engage Totals   ]
```

That might be cool.

**Comment by marknye-at-illinois** [comment]
John, that works for me. The only issue with adding unique users to the existing engagement graph is that values are somewhat higher for unique users, which tends to push the collaboration count and login lines to the bottom of the graph. But maybe we don't care about that?

**Comment by marknye-at-illinois** [comment]
example ...
chart 1

**Comment by jhoerr** [comment]
That's a really good point. We should probably keep them separate. Will merge as-is.

**Pull request merged**
